// API names and types remain in English because they are the actual React contract.
// Descriptions are keyed by the source text so shared props need one translation.
const descriptions: Record<string, string> = {
  'Inline styles for root, row, key, value, actions and link.': '可为 root、row、key、value、actions 和 link 指定行内样式。',
  'CSS classes for root, row, key, value, actions and link.': '可为 root、row、key、value、actions 和 link 指定 CSS 类名。',
  'Inline styles for root, caption, head, body, row, header and cell.': '可为 root、caption、head、body、row、header 和 cell 指定行内样式。',
  'CSS classes for root, caption, head, body, row, header and cell.': '可为 root、caption、head、body、row、header 和 cell 指定 CSS 类名。',
  'Inline styles for root, item, nameAndHint, link, hint and status.': '可为 root、item、nameAndHint、link、hint 和 status 指定行内样式。',
  'CSS classes for root, item, nameAndHint, link, hint and status.': '可为 root、item、nameAndHint、link、hint 和 status 指定 CSS 类名。',
  'GOV.UK spacing around the section break.': '分隔线周围的 GOV.UK 间距。',
  'Show the divider line; false leaves a spacing-only break.': '显示分隔线；设为 false 时仅保留间距。',
  'Native horizontal rule element.': '原生水平分隔线元素。',
  'Initial values for registered fields.': '已注册字段的初始值。',
  'Called when every field passes validation.': '所有字段通过校验时调用。',
  'Called when submission finds errors.': '提交时发现错误后调用。',
  'Optional form-level validation for related fields.': '用于关联字段的可选表单级校验。',
  'Heading displayed above validation links.': '显示在校验错误链接上方的标题。',
  'Native field name used to read its submitted value.': '用于读取提交值的原生字段名称。',
  'Required, pattern or custom validation rules checked on submit.': '提交时检查的必填、正则或自定义校验规则。',
  'Read all values for a checkbox group.': '读取复选框组的所有选中值。',
  'ID targeted from the error summary for grouped fields.': '错误摘要指向分组字段时使用的 ID。',
  'Native form element.': '原生表单元素。',
  'Accessible loading status.': '供辅助技术读取的加载状态。',
  'Accessible name for the action menu.': '操作菜单的无障碍名称。',
  'Accessible name for the menu.': '菜单的无障碍名称。',
  'Accessible name of the close button.': '关闭按钮的无障碍名称。',
  'Actions shown in the menu.': '菜单中显示的操作。',
  'Actions with key, label, optional href, onClick and disabled.': '操作条目包含 key、标签及可选的 href、onClick 和 disabled。',
  'Allow backdrop clicks to request closure.': '允许点击背景请求关闭。',
  'Called after an action is activated.': '激活操作后调用。',
  'Called after an item is activated.': '激活条目后调用。',
  'Called when Escape is pressed.': '按下 Escape 时调用。',
  'Called when the menu requests a state change.': '菜单请求改变状态时调用。',
  'Called when the page changes.': '页码变化时调用。',
  'Called when the selection changes.': '选中项变化时调用。',
  'Called when the sort changes.': '排序变化时调用。',
  'Called when the user requests closure; update open in the parent.': '用户请求关闭时调用；父组件应更新 open。',
  'Column definitions; add sorter for sortable headers.': '列定义；可排序表头需提供 sorter。',
  'Content displayed when there are no records.': '没有记录时显示的内容。',
  'Controlled or initial column and direction.': '受控或初始的排序列与方向。',
  'Controlled or initial open state.': '受控或初始的展开状态。',
  'Controlled or initial selected row keys.': '受控或初始的选中行 key。',
  'Controls whether the dialog is shown.': '控制对话框是否显示。',
  'Dialog content.': '对话框内容。',
  'Dropdown root element.': 'Dropdown 根元素。',
  'Empty state root element.': '空状态根元素。',
  'Focus the first enabled action on mount.': '挂载时聚焦第一个可用操作。',
  'Loading root element.': 'Loading 根元素。',
  'Local page size and optional controlled page.': '本地分页大小和可选的受控页码。',
  'Menu root element.': 'Menu 根元素。',
  'Native dialog element.': '原生 dialog 元素。',
  'Number of skeleton rows.': '骨架屏行数。',
  'Optional action area.': '可选的操作区域。',
  'Optional decorative graphic.': '可选的装饰性图形。',
  'Optional guidance beneath the title.': '标题下方的可选说明。',
  'Question shown as the fieldset legend.': '作为 fieldset 图例显示的问题。',
  'Records displayed by the table.': '表格显示的记录。',
  'Short explanation of the empty state.': '空状态的简短说明。',
  'Show row and current-page selection controls.': '显示行选择和当前页全选控件。',
  'Stable unique key for each row.': '每行稳定且唯一的 key。',
  'Table element.': '表格元素。',
  'Trigger button content.': '触发按钮的内容。',
  'Visible heading and accessible dialog name.': '可见标题和对话框的无障碍名称。',
  'Visual loading treatment.': '加载状态的视觉样式。',
  'Controlled value.': '受控值。',
  'Called when the value changes.': '值变化时调用。',
  'Accordion sections with a key, heading, optional summary and content.': '手风琴区块，包括 key、标题、可选摘要和内容。',
  'Label used to expand every section.': '用于展开全部区块的标签。',
  'Optional controlled list of expanded section keys.': '可选的受控已展开区块 key 列表。',
  'Called after a section or the show-all control is toggled.': '切换区块或全部展开控件后调用。',
  'Accordion root element.': '手风琴根元素。',
  'Destination for the previous step.': '上一步的目标地址。',
  'Link label.': '链接标签。',
  'Ordered breadcrumb links and a text-only current item.': '按顺序排列的面包屑链接，以及仅显示文字的当前项。',
  'Show a shortened trail on small screens.': '在小屏幕上显示缩短的导航路径。',
  'Accessible navigation label.': '无障碍导航标签。',
  'Button label.': '按钮标签。',
  'Visual hierarchy.': '视觉层级。',
  'Renders a link styled as a button.': '将链接渲染为按钮样式。',
  'Native button type when href is not supplied.': '未提供 href 时使用的原生按钮类型。',
  'Use start button styling and the arrow icon.': '使用开始按钮样式和箭头图标。',
  'Disables a native button and adds aria-disabled. Not available for links.': '禁用原生按钮并添加 aria-disabled；不适用于链接。',
  'Ignore another button click within one second. Not applied to links.': '忽略一秒内的再次点击；不适用于链接。',
  'Shortcut for the warning treatment.': '快速启用警告样式。',
  'Textarea label.': '多行文本框标签。',
  'Maximum number of characters.': '允许的最大字符数。',
  'Optional word limit instead of character limit.': '可选的词数限制，可替代字符数限制。',
  'Checkbox labels, values, hints and conditional content.': '复选框标签、值、提示和条件内容。',
  'Controlled selected values.': '受控的选中值。',
  'Called with all selected values.': '使用所有选中值调用。',
  'Group fieldset.': '分组 fieldset。',
  'Refs for individual options, keyed by option value.': '按选项值索引的各选项 ref。',
  'Native event handlers and attributes shared by each checkbox.': '各复选框共用的原生事件处理器和属性。',
  'Cookie explanation.': 'Cookie 说明。',
  'Called when analytics cookies are accepted.': '接受分析 Cookie 时调用。',
  'Called when analytics cookies are rejected.': '拒绝分析 Cookie 时调用。',
  'Question for the complete date.': '完整日期的问题文字。',
  'Controlled date value.': '受控日期值。',
  'Called with the complete date value object.': '使用完整日期值对象调用。',
  'Refs for the individual date fields.': '各日期字段的 ref。',
  'Native event handlers and attributes shared by the day, month and year fields.': '日、月、年字段共用的原生事件处理器和属性。',
  'Visible disclosure label.': '可见的展开标签。',
  'Content revealed when expanded.': '展开后显示的内容。',
  'Initial native open state.': '原生初始展开状态。',
  'Native toggle event; read currentTarget.open for the new state.': '原生切换事件；从 currentTarget.open 读取新状态。',
  'Native details element.': '原生 details 元素。',
  'Clear, concise error text.': '清晰、简短的错误文字。',
  'Prefix announced by assistive technology.': '辅助技术播报的前缀。',
  'Summary heading.': '摘要标题。',
  'Error text and optional target links.': '错误文字和可选的目标链接。',
  'Action label.': '操作标签。',
  'Safe destination.': '安全的目标地址。',
  'Records the quick usefulness response.': '记录“是否有用”的简短反馈。',
  'Receives a problem report.': '接收问题报告。',
  'Called when the problem report form opens or closes.': '问题报告表单打开或关闭时调用。',
  'Feedback section root element.': '反馈区块根元素。',
  'Accessible name for the group.': '分组的无障碍名称。',
  'Related form controls.': '相关表单控件。',
  'Optional legend emphasis.': '可选的图例强调样式。',
  'Wrap the legend content in a level-one heading.': '将图例内容包在一级标题中。',
  'Visible file input label.': '可见的文件输入标签。',
  'Accepted format and size guidance.': '文件格式和大小要求说明。',
  'Validation error.': '验证错误。',
  'Native accepted file types.': '原生文件类型限制。',
  'Grouped footer navigation.': '分组的页脚导航。',
  'Supporting links.': '辅助链接。',
  'Supporting policy links.': '辅助政策链接。',
  'Optional licence or service information.': '可选的许可或服务信息。',
  'Optional organisation copyright statement.': '可选的机构版权声明。',
  'Service or organisation name.': '服务或机构名称。',
  'Optional image or SVG shown before the title.': '标题前显示的可选图片或 SVG。',
  'Home destination.': '首页目标地址。',
  'Use a full-width container.': '使用全宽容器。',
  'GOV.UK home destination.': 'GOV.UK 首页目标地址。',
  'Use a full-width header container.': '使用全宽页眉容器。',
  'Optional product identity shown beside the GOV.UK logotype.': '在 GOV.UK 标志旁显示的可选产品名称。',
  'Supporting content.': '补充内容。',
  'Languages, links and current state.': '语言、链接和当前状态。',
  'Languages, links, language tags and current state.': '语言、链接、语言标记和当前状态。',
  'Banner heading.': '横幅标题。',
  'Banner content.': '横幅内容。',
  'Semantic banner type.': '语义化横幅类型。',
  'Current page, starting at 1.': '当前页，从 1 开始。',
  'Number of pages.': '总页数。',
  'Called with the selected page number.': '使用选中的页码调用。',
  'Previous destination and optional descriptive label for block navigation.': '区块导航的上一页地址及可选说明标签。',
  'Next destination and optional descriptive label for block navigation.': '区块导航的下一页地址及可选说明标签。',
  'Builds a link for each numbered page.': '为每个页码生成链接。',
  'Panel heading.': '面板标题。',
  'Supporting panel content.': '面板补充内容。',
  'Panel style and purpose.': '面板样式和用途。',
  'Semantic heading level.': '语义化标题级别。',
  'Buttons or links shown in the panel actions area; use inverse styles for interruption panels.': '面板操作区显示的按钮或链接；中断面板应使用反色样式。',
  'Input label.': '输入框标签。',
  'Reveal control label.': '显示内容按钮的标签。',
  'Mask control label.': '隐藏内容按钮的标签。',
  'Called when the show/hide control changes the input type.': '显示／隐藏按钮改变输入类型时调用。',
  'Native password input; standard input event handlers are also supported.': '原生密码输入框；也支持标准输入事件处理器。',
  'Short explanation and feedback link.': '简短说明和反馈链接。',
  'Phase label, usually Alpha or Beta.': '阶段标签，通常为 Alpha 或 Beta。',
  'Additional class for the banner container.': '横幅容器的附加类名。',
  'Question for the group.': '分组的问题文字。',
  'Radio options, hints and conditional content.': '单选选项、提示和条件内容。',
  'Native event handlers and attributes shared by each radio.': '各单选按钮共用的原生事件处理器和属性。',
  'Accessible search field label.': '搜索字段的无障碍标签。',
  'Optional supporting guidance.': '可选的补充说明。',
  'Optional guidance.': '可选说明。',
  'Side of the input containing the icon.': '图标位于输入框的哪一侧。',
  'Decorative icon. Pass null to hide it.': '装饰性图标；传入 null 可隐藏。',
  'Hide the label visually while keeping it available to assistive technology.': '视觉上隐藏标签，但仍供辅助技术读取。',
  'Use controlled or uncontrolled search input behaviour.': '使用受控或非受控搜索输入模式。',
  'Select label.': '下拉选择框标签。',
  'Labels and values.': '标签和值。',
  'Service identity.': '服务标识。',
  'Optional service home destination.': '可选的服务首页地址。',
  'Optional click handler for the service name.': '服务名称的可选点击处理器。',
  'Navigation items accept optional href and onClick. The handler can prevent navigation.': '导航项可提供 href 和 onClick；处理器可以阻止导航。',
  'Optional controlled state of the mobile menu.': '可选的受控移动菜单状态。',
  'Called when the mobile menu button is pressed.': '按下移动菜单按钮时调用。',
  'Service navigation root element.': '服务导航根元素。',
  'ID of the main content area.': '主要内容区域的 ID。',
  'Key, value and optional contextual actions.': '键、值以及可选的上下文操作。',
  'Show separators between rows.': '在各行之间显示分隔线。',
  'Accessible table title.': '表格的无障碍标题。',
  'Column titles, record keys, rowHeader flags and render functions.': '列标题、记录 key、rowHeader 标记和渲染函数。',
  'Rows to render.': '要渲染的数据行。',
  'Tab keys, labels and panel content.': '标签页 key、标签和面板内容。',
  'Controlled active tab.': '受控的当前标签页。',
  'Initial active tab.': '初始选中的标签页。',
  'Called with the selected tab key.': '使用选中的标签页 key 调用。',
  'Short status text.': '简短的状态文字。',
  'Status colour treatment.': '状态颜色样式。',
  'Task title, destination, hint and status.': '任务标题、目标地址、提示和状态。',
  'Visible and accessible input label.': '可见且可供辅助技术读取的输入标签。',
  'Expected-answer width.': '根据预期答案设置的宽度。',
  'Visual and semantic error state.': '视觉和语义化的错误状态。',
  'Initial visible height.': '初始可见高度。',
  'Warning message.': '警告文字。',
  'Prefix for assistive technology.': '供辅助技术读取的前缀。',
  'Optional bold label above the content.': '内容上方可选的加粗标签。',
  'Supporting content inside the note.': '说明框中的补充内容。',
  'Additional CSS class for local spacing or styling.': '用于局部间距或样式的附加 CSS 类名。',
  'Note root element.': 'Note 根元素。',
  'Visible heading and navigation label.': '可见标题及导航标签。',
  'Links can have nested children; items without href or onClick are group headings.': '链接可以包含嵌套子项；没有 href 或 onClick 的项目是分组标题。',
  'Key of the current link and branch.': '当前链接及分支的 key。',
  'Add expand and collapse controls to items with children.': '为含子项的项目添加展开和收起控件。',
  'Optional link renderer for a client-side router.': '用于客户端路由的可选链接渲染函数。',
  'Called when a collapsible group is toggled.': '折叠分组切换时调用。',
  'Sidebar navigation root element.': 'Sidebar 导航根元素。',
  'Short text or other inline content displayed inside the box.': '标签框中显示的简短文字或其他行内内容。',
  'Additional CSS class for positioning or local styling.': '用于定位或局部样式的附加 CSS 类名。',
}

export function chineseApiDescription(description: string): string {
  return descriptions[description] ?? description
}
