// API names and types remain in English because they are the actual React contract.
// Descriptions are keyed by the source text so shared props need one translation.
const descriptions: Record<string, string> = {
  'Inline styles for root, row, key, value, actions and link.': '可为 root、row、key、value、actions 和 link 指定行内样式。',
  'CSS classes for root, row, key, value, actions and link.': '可为 root、row、key、value、actions 和 link 指定 CSS 类名。',
  'Inline styles for root, caption, head, body, row, header and cell.': '可为 root、caption、head、body、row、header 和 cell 指定行内样式。',
  'CSS classes for root, caption, head, body, row, header and cell.': '可为 root、caption、head、body、row、header 和 cell 指定 CSS 类名。',
  'Inline styles for root, item, nameAndHint, link, hint and status.': '可为 root、item、nameAndHint、link、hint 和 status 指定行内样式。',
  'CSS classes for root, item, nameAndHint, link, hint and status.': '可为 root、item、nameAndHint、link、hint 和 status 指定 CSS 类名。',
  'GOV.UK spacing around the section break.': '分隔线周围的 GOV.UK 间距。',
  'Show the divider line; false leaves a spacing-only break.': '显示分隔线；设为 false 时仅保留间距。',
  'Native horizontal rule element.': '原生水平分隔线元素。',
  'Initial values for registered fields.': '已注册字段的初始值。',
  'Called when every field passes validation.': '所有字段通过校验时调用。',
  'Called when submission finds errors.': '提交时发现错误后调用。',
  'Optional form-level validation for related fields.': '用于关联字段的可选表单级校验。',
  'Heading displayed above validation links.': '显示在校验错误链接上方的标题。',
  'Native field name used to read its submitted value.': '用于读取提交值的原生字段名称。',
  'Required, pattern, min, max, len, type, whitespace or custom rules; checked according to validateTrigger.': '必填、正则、min、max、len、type、whitespace 或自定义规则；按 validateTrigger 设定的时机校验。',
  'Read all values for a checkbox group.': '读取复选框组的所有选中值。',
  'ID targeted from the error summary for grouped fields.': '错误摘要指向分组字段时使用的 ID。',
  'Native form element.': '原生表单元素。',
  'Accessible loading status.': '供辅助技术读取的加载状态。',
  'Accessible name for the action menu.': '操作菜单的无障碍名称。',
  'Accessible name for the menu.': '菜单的无障碍名称。',
  'Accessible name of the close button.': '关闭按钮的无障碍名称。',
  'Actions shown in the menu.': '菜单中显示的操作。',
  'Actions with key, label, optional href, onClick, icon, danger styling or disabled; set type to divider for a separator.': '操作条目包含 key、标签及可选的 href、onClick、icon、danger 样式和 disabled；将 type 设为 divider 可显示分隔符。',
  'Allow backdrop clicks to request closure.': '允许点击背景请求关闭。',
  'Called after an action is activated.': '激活操作后调用。',
  'Called after an item is activated.': '激活条目后调用。',
  'Called when Escape is pressed.': '按下 Escape 时调用。',
  'Called when the menu requests a state change.': '菜单请求改变状态时调用。',
  'Called when the page changes.': '页码变化时调用。',
  'Called when the selection changes.': '选中项变化时调用。',
  'Called when the sort changes.': '排序变化时调用。',
  'Called when the user requests closure; update open in the parent.': '用户请求关闭时调用；父组件应更新 open。',
  'Column definitions; add sorter for sortable headers.': '列定义；可排序表头需提供 sorter。',
  'Content displayed when there are no records.': '没有记录时显示的内容。',
  'Controlled or initial column and direction.': '受控或初始的排序列与方向。',
  'Controlled or initial open state.': '受控或初始的展开状态。',
  'Controlled or initial selected row keys.': '受控或初始的选中行 key。',
  'Controls whether the dialog is shown.': '控制对话框是否显示。',
  'Dialog content.': '对话框内容。',
  'Dropdown root element.': 'Dropdown 根元素。',
  'Empty state root element.': '空状态根元素。',
  'Focus the first enabled action on mount.': '挂载时聚焦第一个可用操作。',
  'Loading root element.': 'Loading 根元素。',
  'Local page size and optional controlled page.': '本地分页大小和可选的受控页码。',
  'Menu root element.': 'Menu 根元素。',
  'Native dialog element.': '原生 dialog 元素。',
  'Number of skeleton rows.': '骨架屏行数。',
  'Size of the spinner or skeleton rows.': '旋转指示器或骨架屏行的尺寸。',
  'Optional action area; when omitted and onOk or custom okText or cancelText is supplied, a built-in footer is rendered.': '可选的操作区域；未提供 footer 但提供了 onOk 或自定义 okText／cancelText 时，会渲染内置页脚。',
  'Optional action area.': '可选的操作区域。',
  'Dialog width in pixels or any CSS length.': '对话框宽度，单位为像素或任意 CSS 长度。',
  'Centre the dialog vertically.': '在垂直方向上居中对话框。',
  'Allow Escape to request closure.': '允许按 Escape 请求关闭。',
  'Show the close button.': '显示关闭按钮。',
  'Label of the built-in footer confirm action.': '内置页脚确认操作的标签。',
  'Label of the built-in footer cancel action.': '内置页脚取消操作的标签。',
  'Called by the built-in footer confirm action; a returned promise keeps the confirm button loading until it settles.': '内置页脚确认操作被按下时调用；返回的 Promise 会让确认按钮保持加载状态直到其结束。',
  'Loading state of the built-in footer confirm button.': '内置页脚确认按钮的加载状态。',
  'Remove the dialog content from the DOM after the dialog has been closed once.': '对话框关闭过一次后，将其内容从 DOM 中移除。',
  'Delay in milliseconds before the loading state is shown.': '显示加载状态前的延迟毫秒数。',
  'Overlay the entire viewport.': '覆盖整个视口。',
  'Interaction that opens the menu.': '打开菜单的交互方式。',
  'Where the menu appears relative to the trigger.': '菜单相对于触发器出现的位置。',
  'Where the tooltip appears relative to the trigger.': '提示框相对于触发器出现的位置。',
  'Interaction that shows the tooltip.': '显示提示框的交互方式。',
  'Called when the tooltip requests a state change.': '提示框请求改变状态时调用。',
  'Content of the tooltip.': '提示框的内容。',
  'Single element that triggers the tooltip.': '触发提示框的单个元素。',
  'Tooltip wrapper element.': '提示框外层元素。',
  'Controlled checked state.': '受控的选中状态。',
  'Initial checked state.': '初始选中状态。',
  'Called with the new state when the toggle is pressed.': '按下开关时使用新状态调用。',
  'Prevent interaction.': '阻止交互。',
  'Show a spinner in the handle and block interaction.': '在滑块中显示旋转指示器并阻止交互。',
  'Toggle size.': '开关尺寸。',
  'Content shown in the track while checked.': '选中时轨道内显示的内容。',
  'Content shown in the track while unchecked.': '未选中时轨道内显示的内容。',
  'A string becomes a visually hidden label; other content renders beside the toggle.': '字符串会成为视觉隐藏的标签；其他内容渲染在开关旁边。',
  'Accessible name when children are not a plain string.': '当子元素不是纯字符串时使用的无障碍名称。',
  'Native toggle button.': '原生开关按钮。',
  'Column definitions with optional sorter, filters, onFilter, filterMultiple and onCell.': '列定义，可选提供 sorter、filters、onFilter、filterMultiple 和 onCell。',
  'Replace the body with a loading indicator and mark the table busy.': '用加载指示器替换表体内容，并将表格标记为忙碌状态。',
  'Controlled or initial filter values by column key.': '按列 key 受控或初始的筛选值。',
  'Called when a column filter changes.': '某列筛选变化时调用。',
  'Row expansion with expandedRowRender, optional rowExpandable and controlled or initial expanded row keys.': '行展开配置，包含 expandedRowRender、可选的 rowExpandable，以及受控或初始的展开行 key。',
  'Additional class for each row.': '为每行附加的 CSS 类名。',
  'Native attributes and handlers applied to each row.': '应用到每行的原生属性和事件处理器。',
  'Show record totals beside the pagination; a function renders custom text.': '在分页旁显示记录总数；传入函数可渲染自定义文字。',
  'Let users change the page size.': '允许用户更改每页条数。',
  'Page sizes offered by the size changer.': '每页条数选择器提供的可选条数。',
  'Called when the page size changes.': '每页条数变化时调用。',
  'Tab keys, labels and panel content. Items can be disabled to make their tab non-interactive.': '标签页 key、标签和面板内容。条目可设为 disabled，使其标签不可交互。',
  'Remove inactive panel content from the DOM instead of hiding it.': '将非活动面板内容从 DOM 中移除，而不是隐藏。',
  'When registered rules run; pass an array to validate on several events.': '已注册规则的校验时机；传入数组可在多个事件上校验。',
  'Move focus to the first field with an error after a failed submission.': '提交失败后将焦点移到第一个有错误的字段。',
  'Disable every field inside the form.': '禁用表单内的所有字段。',
  'Show a spinner, block clicks and set aria-busy while work is in progress.': '任务进行中显示旋转指示器、阻止点击并设置 aria-busy。',
  'Icon rendered inside the button; replaced by the spinner while loading.': '渲染在按钮内的图标；加载时被旋转指示器替换。',
  'Side of the label where the icon appears.': '图标出现在标签的哪一侧。',
  'Disables the button and adds aria-disabled. Links render inert and ignore clicks.': '禁用按钮并添加 aria-disabled；链接渲染为 inert 状态并忽略点击。',
  'Content shown before the input, such as a currency symbol.': '显示在输入框之前的内容，例如货币符号。',
  'Content shown after the input.': '显示在输入框之后的内容。',
  'Show a clear button while the input has a value.': '输入框有内容时显示清除按钮。',
  'Called with the current value when Enter is pressed or the search button is clicked.': '按下回车或点击搜索按钮时，使用当前值调用。',
  'Show a spinner in place of the icon.': '在图标位置显示旋转指示器。',
  'Content of a dedicated search button shown beside the field; pressing it triggers onSearch.': '显示在字段旁的专用搜索按钮内容；点击会触发 onSearch。',
  'Render a multi-select listbox; value and onChange use arrays of selected values.': '渲染多选列表框；value 和 onChange 使用选中值的数组。',
  'Filter the options with a search field. Multiple mode only.': '通过搜索字段筛选选项。仅多选模式可用。',
  'Show a loading state in place of the options. Multiple mode only.': '在选项位置显示加载状态。仅多选模式可用。',
  'Grow the height to fit the content, optionally between minRows and maxRows.': '高度随内容自动增长，可选限制在 minRows 与 maxRows 之间。',
  'Add a close button to the tag.': '为标签添加关闭按钮。',
  'Called when the close button is pressed.': '按下关闭按钮时调用。',
  'Optional decorative graphic.': '可选的装饰性图形。',
  'Optional guidance beneath the title.': '标题下方的可选说明。',
  'Question shown as the fieldset legend.': '作为 fieldset 图例显示的问题。',
  'Records displayed by the table.': '表格显示的记录。',
  'Short explanation of the empty state.': '空状态的简短说明。',
  'Show row and current-page selection controls.': '显示行选择和当前页全选控件。',
  'Stable unique key for each row.': '每行稳定且唯一的 key。',
  'Table element.': '表格元素。',
  'Trigger button content.': '触发按钮的内容。',
  'Visible heading and accessible dialog name.': '可见标题和对话框的无障碍名称。',
  'Visual loading treatment.': '加载状态的视觉样式。',
  'Controlled value.': '受控值。',
  'Called when the value changes.': '值变化时调用。',
  'Accordion sections with a key, heading, optional summary and content.': '手风琴区块，包括 key、标题、可选摘要和内容。',
  'Label used to expand every section.': '用于展开全部区块的标签。',
  'Optional controlled list of expanded section keys.': '可选的受控已展开区块 key 列表。',
  'Called after a section or the show-all control is toggled.': '切换区块或全部展开控件后调用。',
  'Accordion root element.': '手风琴根元素。',
  'Destination for the previous step.': '上一步的目标地址。',
  'Link label.': '链接标签。',
  'Ordered breadcrumb links and a text-only current item.': '按顺序排列的面包屑链接，以及仅显示文字的当前项。',
  'Show a shortened trail on small screens.': '在小屏幕上显示缩短的导航路径。',
  'Accessible navigation label.': '无障碍导航标签。',
  'Button label.': '按钮标签。',
  'Visual hierarchy.': '视觉层级。',
  'Renders a link styled as a button.': '将链接渲染为按钮样式。',
  'Native button type when href is not supplied.': '未提供 href 时使用的原生按钮类型。',
  'Use start button styling and the arrow icon.': '使用开始按钮样式和箭头图标。',
  'Ignore another button click within one second. Not applied to links.': '忽略一秒内的再次点击；不适用于链接。',
  'Shortcut for the warning treatment.': '快速启用警告样式。',
  'Textarea label.': '多行文本框标签。',
  'Maximum number of characters.': '允许的最大字符数。',
  'Optional word limit instead of character limit.': '可选的词数限制，可替代字符数限制。',
  'Checkbox labels, values, hints and conditional content.': '复选框标签、值、提示和条件内容。',
  'Controlled selected values.': '受控的选中值。',
  'Called with all selected values.': '使用所有选中值调用。',
  'Group fieldset.': '分组 fieldset。',
  'Refs for individual options, keyed by option value.': '按选项值索引的各选项 ref。',
  'Native event handlers and attributes shared by each checkbox.': '各复选框共用的原生事件处理器和属性。',
  'Cookie explanation.': 'Cookie 说明。',
  'Called when analytics cookies are accepted.': '接受分析 Cookie 时调用。',
  'Called when analytics cookies are rejected.': '拒绝分析 Cookie 时调用。',
  'Question for the complete date.': '完整日期的问题文字。',
  'Controlled date value.': '受控日期值。',
  'Called with the complete date value object.': '使用完整日期值对象调用。',
  'Refs for the individual date fields.': '各日期字段的 ref。',
  'Native event handlers and attributes shared by the day, month and year fields.': '日、月、年字段共用的原生事件处理器和属性。',
  'Visible disclosure label.': '可见的展开标签。',
  'Content revealed when expanded.': '展开后显示的内容。',
  'Initial native open state.': '原生初始展开状态。',
  'Native toggle event; read currentTarget.open for the new state.': '原生切换事件；从 currentTarget.open 读取新状态。',
  'Native details element.': '原生 details 元素。',
  'Clear, concise error text.': '清晰、简短的错误文字。',
  'Prefix announced by assistive technology.': '辅助技术播报的前缀。',
  'Summary heading.': '摘要标题。',
  'Error text and optional target links.': '错误文字和可选的目标链接。',
  'Action label.': '操作标签。',
  'Safe destination.': '安全的目标地址。',
  'Records the quick usefulness response.': '记录“是否有用”的简短反馈。',
  'Receives a problem report.': '接收问题报告。',
  'Called when the problem report form opens or closes.': '问题报告表单打开或关闭时调用。',
  'Feedback section root element.': '反馈区块根元素。',
  'Accessible name for the group.': '分组的无障碍名称。',
  'Related form controls.': '相关表单控件。',
  'Optional legend emphasis.': '可选的图例强调样式。',
  'Wrap the legend content in a level-one heading.': '将图例内容包在一级标题中。',
  'Visible file input label.': '可见的文件输入标签。',
  'Accepted format and size guidance.': '文件格式和大小要求说明。',
  'Validation error.': '验证错误。',
  'Native accepted file types.': '原生文件类型限制。',
  'Grouped footer navigation.': '分组的页脚导航。',
  'Supporting links.': '辅助链接。',
  'Supporting policy links.': '辅助政策链接。',
  'Optional licence or service information.': '可选的许可或服务信息。',
  'Optional organisation copyright statement.': '可选的机构版权声明。',
  'Service or organisation name.': '服务或机构名称。',
  'Optional image or SVG shown before the title.': '标题前显示的可选图片或 SVG。',
  'Home destination.': '首页目标地址。',
  'Use a full-width container.': '使用全宽容器。',
  'GOV.UK home destination.': 'GOV.UK 首页目标地址。',
  'Use a full-width header container.': '使用全宽页眉容器。',
  'Optional product identity shown beside the GOV.UK logotype.': '在 GOV.UK 标志旁显示的可选产品名称。',
  'Supporting content.': '补充内容。',
  'Languages, links and current state.': '语言、链接和当前状态。',
  'Languages, links, language tags and current state.': '语言、链接、语言标记和当前状态。',
  'Banner heading.': '横幅标题。',
  'Banner content.': '横幅内容。',
  'Semantic banner type.': '语义化横幅类型。',
  'Current page, starting at 1.': '当前页，从 1 开始。',
  'Number of pages.': '总页数。',
  'Called with the selected page number.': '使用选中的页码调用。',
  'Previous destination and optional descriptive label for block navigation.': '区块导航的上一页地址及可选说明标签。',
  'Next destination and optional descriptive label for block navigation.': '区块导航的下一页地址及可选说明标签。',
  'Builds a link for each numbered page.': '为每个页码生成链接。',
  'Panel heading.': '面板标题。',
  'Supporting panel content.': '面板补充内容。',
  'Panel style and purpose.': '面板样式和用途。',
  'Semantic heading level.': '语义化标题级别。',
  'Buttons or links shown in the panel actions area; use inverse styles for interruption panels.': '面板操作区显示的按钮或链接；中断面板应使用反色样式。',
  'Input label.': '输入框标签。',
  'Reveal control label.': '显示内容按钮的标签。',
  'Mask control label.': '隐藏内容按钮的标签。',
  'Called when the show/hide control changes the input type.': '显示／隐藏按钮改变输入类型时调用。',
  'Native password input; standard input event handlers are also supported.': '原生密码输入框；也支持标准输入事件处理器。',
  'Short explanation and feedback link.': '简短说明和反馈链接。',
  'Phase label, usually Alpha or Beta.': '阶段标签，通常为 Alpha 或 Beta。',
  'Additional class for the banner container.': '横幅容器的附加类名。',
  'Question for the group.': '分组的问题文字。',
  'Radio options, hints and conditional content.': '单选选项、提示和条件内容。',
  'Native event handlers and attributes shared by each radio.': '各单选按钮共用的原生事件处理器和属性。',
  'Accessible search field label.': '搜索字段的无障碍标签。',
  'Optional supporting guidance.': '可选的补充说明。',
  'Optional guidance.': '可选说明。',
  'Side of the input containing the icon.': '图标位于输入框的哪一侧。',
  'Decorative icon. Pass null to hide it.': '装饰性图标；传入 null 可隐藏。',
  'Hide the label visually while keeping it available to assistive technology.': '视觉上隐藏标签，但仍供辅助技术读取。',
  'Use controlled or uncontrolled search input behaviour.': '使用受控或非受控搜索输入模式。',
  'Select label.': '下拉选择框标签。',
  'Labels and values.': '标签和值。',
  'Service identity.': '服务标识。',
  'Optional service home destination.': '可选的服务首页地址。',
  'Optional click handler for the service name.': '服务名称的可选点击处理器。',
  'Navigation items accept optional href and onClick. The handler can prevent navigation.': '导航项可提供 href 和 onClick；处理器可以阻止导航。',
  'Optional controlled state of the mobile menu.': '可选的受控移动菜单状态。',
  'Called when the mobile menu button is pressed.': '按下移动菜单按钮时调用。',
  'Service navigation root element.': '服务导航根元素。',
  'ID of the main content area.': '主要内容区域的 ID。',
  'Key, value and optional contextual actions.': '键、值以及可选的上下文操作。',
  'Show separators between rows.': '在各行之间显示分隔线。',
  'Accessible table title.': '表格的无障碍标题。',
  'Column titles, record keys, rowHeader flags and render functions.': '列标题、记录 key、rowHeader 标记和渲染函数。',
  'Rows to render.': '要渲染的数据行。',
  'Controlled active tab.': '受控的当前标签页。',
  'Initial active tab.': '初始选中的标签页。',
  'Called with the selected tab key.': '使用选中的标签页 key 调用。',
  'Short status text.': '简短的状态文字。',
  'Status colour treatment.': '状态颜色样式。',
  'Task title, destination, hint and status.': '任务标题、目标地址、提示和状态。',
  'Visible and accessible input label.': '可见且可供辅助技术读取的输入标签。',
  'Expected-answer width.': '根据预期答案设置的宽度。',
  'Visual and semantic error state.': '视觉和语义化的错误状态。',
  'Initial visible height.': '初始可见高度。',
  'Warning message.': '警告文字。',
  'Prefix for assistive technology.': '供辅助技术读取的前缀。',
  'Optional bold label above the content.': '内容上方可选的加粗标签。',
  'Supporting content inside the note.': '说明框中的补充内容。',
  'Additional CSS class for local spacing or styling.': '用于局部间距或样式的附加 CSS 类名。',
  'Note root element.': 'Note 根元素。',
  'Visible heading and navigation label.': '可见标题及导航标签。',
  'Links can have nested children; items without href or onClick are group headings.': '链接可以包含嵌套子项；没有 href 或 onClick 的项目是分组标题。',
  'Key of the current link and branch.': '当前链接及分支的 key。',
  'Add expand and collapse controls to items with children.': '为含子项的项目添加展开和收起控件。',
  'Optional link renderer for a client-side router.': '用于客户端路由的可选链接渲染函数。',
  'Called when a collapsible group is toggled.': '折叠分组切换时调用。',
  'Sidebar navigation root element.': 'Sidebar 导航根元素。',
  'Short text or other inline content displayed inside the box.': '标签框中显示的简短文字或其他行内内容。',
  'Additional CSS class for positioning or local styling.': '用于定位或局部样式的附加 CSS 类名。',
  'Visual state; error also sets aria-invalid, warning only changes the border colour.': '视觉状态；error 会同时设置 aria-invalid，warning 仅改变边框颜色。',
  'With multiple and name, render a hidden input per selected value so the native form submits them. Multiple mode only.': '与 multiple 和 name 搭配时，为每个选中值渲染一个隐藏输入框，使原生表单提交这些值。仅多选模式。',
  'Checkbox labels, values, hints, conditional content and an exclusive option.': '复选框的标签、值、提示、条件内容以及互斥选项。',
  'Divider text rendered before an exclusive option.': '渲染在互斥选项之前的分隔文字。',
  'Aggregate callback for remote data mode, fired after any pagination, sort or filter change.': '远程数据模式的聚合回调，在任何分页、排序或筛选变化后触发。',
  'Called after each open state change.': '每次开合状态变化后调用。',
  'Called once after the dialog closes.': '对话框关闭后调用一次。',
  'Override the built-in validation message templates; supports ${label} and rule value interpolation.': '覆盖内置的校验文案模板；支持 ${label} 及规则值插值。',
  'Bind a Form.useForm() instance to the form for imperative operations.': '将 Form.useForm() 创建的实例绑定到表单，以进行命令式操作。',
  'Create an instance with getFieldValue, getFieldsValue, setFieldValue, setFieldsValue, validateFields, resetFields and submit.': '创建实例，包含 getFieldValue、getFieldsValue、setFieldValue、setFieldsValue、validateFields、resetFields 和 submit 方法。',
  'Render a dynamic group of named fields such as passengers.0, passengers.1.': '渲染一组动态命名字段，如 passengers.0、passengers.1。',
  'Re-validate this field when one of the listed fields changes.': '当列出的任一字段变化时重新校验本字段。',
  'Render a hidden input so the checked state submits with a native form.': '渲染隐藏输入框，使选中状态随原生表单提交。',
  'Semantic alert type.': '语义化警报类型。',
  'Bold heading of the alert.': '警报的加粗标题。',
  'Supporting text beneath the title.': '标题下方的补充说明。',
  'Message content shown between the title and description.': '显示在标题与描述之间的消息内容。',
  'Show a close button.': '显示关闭按钮。',
  'Custom close button text; defaults to a multiplication sign.': '自定义关闭按钮文字；默认为乘号。',
  'Show the icon matching the alert type.': '显示与警报类型匹配的图标。',
  'Alert root element.': 'Alert 根元素。',
  'Steps with key, title, optional description, status, disabled and icon.': '步骤包含 key、标题以及可选的描述、状态、禁用和图标。',
  'Controlled active step index, starting at 0.': '受控的当前步骤索引，从 0 开始。',
  'Initial active step index.': '初始当前步骤索引。',
  'Called with the index of the step the user selected.': '以用户选中步骤的索引调用。',
  'Layout of the step list.': '步骤列表的布局。',
  'Step indicator size.': '步骤指示器尺寸。',
  'Steps list element.': '步骤列表元素。',
  'Progress value between 0 and 100; values outside the range are clamped.': '0 到 100 之间的进度值；超出范围会被截断。',
  'Visual state of the bar; 100% or more always renders as success.': '进度条的视觉状态；达到 100% 及以上始终显示为成功。',
  'Show the percentage next to the bar.': '在进度条旁显示百分比。',
  'Bar size.': '进度条尺寸。',
  'Custom colour of the filled portion.': '自定义已填充部分的颜色。',
  'Progress root element.': 'Progress 根元素。',
  'Result status; one of success, error, info, warning, 403, 404 or 500.': '结果状态：success、error、info、warning、403、404 或 500。',
  'Main result heading.': '结果主标题。',
  'Optional supporting text beneath the title.': '标题下方的可选说明文字。',
  'Override the built-in status icon.': '覆盖内置的状态图标。',
  'Action area such as primary and secondary buttons.': '操作区域，可放置主要和次要按钮。',
  'Optional supporting content beneath the actions.': '操作下方的可选补充内容。',
  'Result root element.': 'Result 根元素。',
  'Image source; initials or a fallback icon are shown otherwise.': '图片地址；缺省时显示首字母或备用图标。',
  "Accessible name for the image variant.": '图片模式下的无障碍名称。',
  'Fallback icon when there is no image or text.': '没有图片或文字时的备用图标。',
  'Initials or short text shown when there is no image.': '没有图片时显示的首字母或简短文字。',
  'Circle or square outline.': '圆形或方形外观。',
  'Named size or pixel size of the avatar.': '头像的命名尺寸或像素尺寸。',
  'Background colour for text or icon avatars.': '文字或图标头像的背景色。',
  'Text and icon colour for text or icon avatars.': '文字或图标头像的文字和图标颜色。',
  'Avatar root element.': 'Avatar 根元素。',
  'Label injected into the field when it has none; also used in validation messages.': '字段本身没有标签时注入的标签；也用于校验文案。',
  'Custom help text; when set it replaces the validation error display.': '自定义帮助文字；设置后替代校验错误的显示。',
  'Supplementary text always shown beneath the field.': '始终显示在字段下方的补充说明。',
  'Controlled single-select value and change callback.': '单选 Select 的受控值与变化回调。',
  'Filter the options with a search field. Renders the custom dropdown in single mode.': '用搜索框筛选选项。单选模式下会渲染自定义下拉。',
  'Show a loading state in place of the options. Custom dropdown modes only.': '在选项位置显示加载状态。仅自定义下拉模式。',
  'With a name, render hidden inputs so the native form submits the selected value.': '传入 name 时渲染隐藏输入框，让原生表单提交选中值。',
  'Mount the popup into a custom container with fixed positioning; useful inside overflow-clipping scroll areas.': '将弹层挂载到自定义容器并使用固定定位；适用于会被 overflow 裁剪的滚动区域。',
  'Visual treatment: line, circle, dashboard or steps.': '视觉形态：线形、环形、仪表盘或步骤条。',
  'Width and height of circle and dashboard types in pixels.': '环形和仪表盘形态的宽高像素值。',
  'Gap of the dashboard type as a percentage of the circumference.': '仪表盘形态缺口占圆周的比例。',
  'Number of segments for the steps type.': '步骤条形态的分段数量。',
  'Render dot indicators instead of numbered circles; finished steps keep a check.': '用圆点替代数字圆圈；已完成步骤仍显示对勾。',
  'Show the default dark backdrop; pass false to let the page show through.': '显示默认的深色遮罩；设为 false 时透出页面内容。',
  'Show a character counter beneath the input, optionally with a maximum.': '在输入框下方显示字符计数，可附带最大值。',
  'Action area aligned to the right of the alert, such as an undo button.': '对齐到警报右侧的操作区域，例如撤销按钮。',
  'Columns and other content inside the grid row.': '网格行中的列或其他内容。',
  'Column width mapped to the matching govuk-grid-column class.': '列宽，映射到对应的 govuk-grid-column 类。',
  'Apply the width only from the desktop breakpoint up; below it the column spans the full row.': '仅在桌面断点及以上应用该宽度；断点以下占满整行。',
  'Content inside the column.': '列中的内容。',
  'Heading shown in the card header.': '显示在卡片页眉中的标题。',
  'Right-aligned content in the header, next to the title.': '页眉中靠右对齐的内容，位于标题旁边。',
  'Body content of the card.': '卡片的正文内容。',
  'Footer content separated from the body by a top border.': '页脚内容，通过上边框与正文分隔。',
  'Highlight the border with the brand colour on hover.': '悬停时使用品牌色高亮边框。',
  'Selected day (controlled); pass null for no selection.': '选中的日期（受控）；传入 null 表示未选择。',
  'Initially selected day when uncontrolled.': '非受控模式下的初始选中日期。',
  'Called with the selected day.': '以选中的日期调用。',
  'Earliest and latest selectable day; out-of-range days are disabled.': '最早和最晚可选择的日期；范围外的日期被禁用。',
  'Extra marker rendered in the bottom-right corner of a day cell.': '渲染在日期单元格右下角的可选标记。',
  'Displayed month (controlled).': '显示的月份（受控）。',
  'Initially displayed month when uncontrolled; defaults to the selected day or today.': '非受控模式下的初始显示月份；默认为选中日期或今天。',
  'Called when the visible month changes.': '可见月份变化时调用。',
  'Show a Today button that jumps back to the current month and day.': '显示 Today 按钮，点击后跳回当前月份和日期。',
  'BCP 47 locale used for weekday and month names; the week starts on Monday.': '用于星期和月份名称的 BCP 47 locale；每周从星期一开始。',
  'Items with key, optional label, description and disabled.': '条目包含 key，以及可选的 label、description 和 disabled。',
  'Keys of items shown in the right-hand target panel (controlled).': '显示在右侧目标面板中的条目 key（受控）。',
  'Initial target keys when uncontrolled.': '非受控模式下的初始目标 key。',
  'Called after items move between panels.': '条目在面板之间移动后调用。',
  'Keys of checked items across both panels (controlled).': '两个面板中所有勾选条目的 key（受控）。',
  'Initial checked keys when uncontrolled.': '非受控模式下的初始勾选 key。',
  'Called when the checked items change.': '勾选条目变化时调用。',
  'Panel titles for the source and target lists.': '源列表和目标列表的面板标题。',
  'Show a search input above each list.': '在每个列表上方显示搜索框。',
  'Custom filter used by both search inputs; defaults to a case-insensitive label match.': '两个搜索框共用的自定义筛选函数；默认对标签做不区分大小写的匹配。',
  'Disable the whole component.': '禁用整个组件。',
  'Labels of the two move buttons. A direction triangle always renders beside the label.': '两个移动按钮的标签。标签旁始终显示方向三角形。',
  'Extra classes merged onto the row or column div.': '合并到行或列 div 上的额外类名。',
  'Row or column div element.': '行或列的 div 元素。',
  'Overrides for the root, header, title, extra, body and actions parts.': '可分别覆盖 root、header、title、extra、body 和 actions 部分。',
  'Card root element.': 'Card 根元素。',
  'Overrides for the root, header, nav, title, grid, weekdays and cell parts.': '可分别覆盖 root、header、nav、title、grid、weekdays 和 cell 部分。',
  'Calendar root element.': 'Calendar 根元素。',
  'Overrides for the root, panel, header, body, list, item, search, operations and operation parts.': '可分别覆盖 root、panel、header、body、list、item、search、operations 和 operation 部分。',
  'Transfer root element.': 'Transfer 根元素。',
  'Minimum and maximum selectable values.': '最小和最大可选值。',
  'Increment between selectable values.': '可选值之间的步进增量。',
  'Render two handles for selecting a [lower, upper] range.': '渲染两个手柄，用于选择 [下限, 上限] 区间。',
  'Anchor the fill at the right edge so it drains as the value grows (depletion style).': '将填充锚定在右端，随数值增大向右收缩（耗尽式）。',
  'Selected value, or [lower, upper] in range mode (controlled).': '选中的值，区间模式下为 [下限, 上限]（受控）。',
  'Initial value when uncontrolled; defaults to min, or [min, max] in range mode.': '非受控模式下的初始值；默认为 min，区间模式下默认为 [min, max]。',
  'Called with the new value when a handle moves.': '手柄移动时以新值调用。',
  'Tick marks rendered under the track, with optional labels.': '渲染在轨道下方的刻度标记，可附带标签。',
  'When to show the current value bubble.': '何时显示当前数值气泡。',
  'Accessible name; in range mode each handle gets `${ariaLabel} minimum` / `maximum`.': '无障碍名称；区间模式下每个手柄会获得 `${ariaLabel} minimum`／`maximum`。',
  'Form field name; in range mode the handles submit as `${name}-lower` / `${name}-upper`.': '表单字段名；区间模式下两个手柄分别以 `${name}-lower`／`${name}-upper` 提交。',
  'Overrides for the root, track, rail, fill, thumb, mark and tooltip parts.': '可分别覆盖 root、track、rail、fill、thumb、mark 和 tooltip 部分。',
  'Slider root element.': 'Slider 根元素。',
  'Controlled value in HH:mm (24-hour) format.': '受控值，格式为 HH:mm（24 小时制）。',
  'Initial value when uncontrolled.': '非受控模式下的初始值。',
  'Called with the raw text while typing and the committed HH:mm value when a time is picked or cleared.': '输入过程中以原始文本调用；选择或清除时间后以提交的 HH:mm 值调用。',
  'Step between minute and hour options in the panel.': '面板中分钟和小时选项之间的步进。',
  'Show a clear button that empties the value.': '显示清空按钮，点击后清空当前值。',
  'Placeholder text shown in the empty input.': '空输入框中显示的占位文本。',
  'Extra status line rendered after the error and included in aria-describedby.': '渲染在错误信息之后的额外状态行，并包含在 aria-describedby 中。',
  'Keep the accessible label while hiding it visually.': '保留可供辅助技术读取的标签，同时在视觉上隐藏。',
  'Extra props spread onto the native input.': '透传到原生输入框的额外属性。',
  'Overrides for the root, label, hint, error, status, control, input, list, option, clear and toggle parts.': '可分别覆盖 root、label、hint、error、status、control、input、list、option、clear 和 toggle 部分。',
  'Native input element.': '原生输入框元素。',
}

export function chineseApiDescription(description: string): string {
  return descriptions[description] ?? description
}
