import { forwardRef, useId, useMemo, useState } from 'react'
import type { CSSProperties, ChangeEvent, FieldsetHTMLAttributes, InputHTMLAttributes, ReactNode, Ref, SelectHTMLAttributes, TextareaHTMLAttributes } from 'react'
import type { SemanticStyling } from './styling'

export const Hint = forwardRef<HTMLDivElement, { id?: string; children: ReactNode; className?: string; style?: CSSProperties }>(function Hint({ id, children, className = '', style }, ref) { return <div ref={ref} id={id} className={`govuk-hint ${className}`.trim()} style={style}>{children}</div> })
export const Label = forwardRef<HTMLLabelElement, { htmlFor?: string; children: ReactNode; size?: 's' | 'm' | 'l' | 'xl'; className?: string; style?: CSSProperties }>(function Label({ htmlFor, children, size, className = '', style }, ref) { return <label ref={ref} className={`govuk-label ${size ? `govuk-label--${size}` : ''} ${className}`.trim()} htmlFor={htmlFor} style={style}>{children}</label> })
export const ErrorMessage = forwardRef<HTMLParagraphElement, { id?: string; children: ReactNode; visuallyHiddenText?: string; className?: string; style?: CSSProperties }>(function ErrorMessage({ id, children, visuallyHiddenText = 'Error:', className = '', style }, ref) { return <p ref={ref} id={id} className={`govuk-error-message ${className}`.trim()} style={style}><span className="govuk-visually-hidden">{visuallyHiddenText}</span> {children}</p> })

export interface FieldsetProps extends FieldsetHTMLAttributes<HTMLFieldSetElement> { legend: ReactNode; legendSize?: 's' | 'm' | 'l' | 'xl'; isPageHeading?: boolean; hint?: ReactNode; error?: ReactNode }
export const Fieldset = forwardRef<HTMLFieldSetElement, FieldsetProps>(function Fieldset({ children, className = '', error, hint, isPageHeading = false, legend, legendSize, ...props }, ref) {
  return <fieldset {...props} ref={ref} className={`govuk-fieldset ${className}`.trim()}><legend className={`govuk-fieldset__legend ${legendSize ? `govuk-fieldset__legend--${legendSize}` : ''}`.trim()}>{isPageHeading ? <h1 className="govuk-fieldset__heading">{legend}</h1> : legend}</legend>{hint && <Hint>{hint}</Hint>}{error && <ErrorMessage>{error}</ErrorMessage>}{children}</fieldset>
})

export interface TextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement>, SemanticStyling<'root' | 'label' | 'hint' | 'error' | 'textarea'> { label: ReactNode; hint?: ReactNode; error?: ReactNode; rows?: number }
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea({ className = '', classNames, error, hint, id, label, rows = 5, style, styles, ...props }, ref) {
  const uid = useId(); const fieldId = id ?? `kvzd-textarea-${uid.replaceAll(':', '')}`; const described = [hint && `${fieldId}-hint`, error && `${fieldId}-error`].filter(Boolean).join(' ')
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''} ${classNames?.root ?? ''}`.trim()} style={styles?.root}><Label htmlFor={fieldId} size="m" className={classNames?.label} style={styles?.label}>{label}</Label>{hint && <Hint id={`${fieldId}-hint`} className={classNames?.hint} style={styles?.hint}>{hint}</Hint>}{error && <ErrorMessage id={`${fieldId}-error`} className={classNames?.error} style={styles?.error}>{error}</ErrorMessage>}<textarea {...props} ref={ref} id={fieldId} rows={rows} aria-describedby={described || undefined} aria-invalid={error ? true : undefined} className={`govuk-textarea ${error ? 'govuk-textarea--error' : ''} ${classNames?.textarea ?? ''} ${className}`.trim()} style={{ ...styles?.textarea, ...style }} /></div>
})

export interface Option { label: ReactNode; value: string; disabled?: boolean }
export interface SelectProps extends Omit<SelectHTMLAttributes<HTMLSelectElement>, 'children'>, SemanticStyling<'root' | 'label' | 'hint' | 'error' | 'select'> { label: ReactNode; hint?: ReactNode; error?: ReactNode; options: Option[]; placeholder?: string }
export const Select = forwardRef<HTMLSelectElement, SelectProps>(function Select({ className = '', classNames, error, hint, id, label, options, placeholder, style, styles, ...props }, ref) {
  const uid = useId(); const fieldId = id ?? `kvzd-select-${uid.replaceAll(':', '')}`; const described = [hint && `${fieldId}-hint`, error && `${fieldId}-error`].filter(Boolean).join(' ')
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''} ${classNames?.root ?? ''}`.trim()} style={styles?.root}><Label htmlFor={fieldId} size="m" className={classNames?.label} style={styles?.label}>{label}</Label>{hint && <Hint id={`${fieldId}-hint`} className={classNames?.hint} style={styles?.hint}>{hint}</Hint>}{error && <ErrorMessage id={`${fieldId}-error`} className={classNames?.error} style={styles?.error}>{error}</ErrorMessage>}<select {...props} ref={ref} id={fieldId} aria-describedby={described || undefined} className={`govuk-select ${error ? 'govuk-select--error' : ''} ${classNames?.select ?? ''} ${className}`.trim()} style={{ ...styles?.select, ...style }}>{placeholder && <option value="">{placeholder}</option>}{options.map((option) => <option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select></div>
})

export interface ChoiceOption extends Option { hint?: ReactNode; conditional?: ReactNode }
export interface ChoiceGroupProps { name: string; legend: ReactNode; options: ChoiceOption[]; value?: string[]; defaultValue?: string[]; onChange?: (value: string[]) => void; hint?: ReactNode; error?: ReactNode; small?: boolean; style?: CSSProperties; inputRefs?: Record<string, Ref<HTMLInputElement>>; inputProps?: Omit<InputHTMLAttributes<HTMLInputElement>, 'checked' | 'value' | 'defaultChecked' | 'defaultValue' | 'onChange' | 'name' | 'type' | 'id'> }
export const Checkboxes = forwardRef<HTMLFieldSetElement, ChoiceGroupProps>(function Checkboxes({ defaultValue = [], error, hint, inputProps, inputRefs, legend, name, onChange, options, small = false, style, value }, ref) {
  const [inner, setInner] = useState(defaultValue); const selected = value ?? inner
  const update = (optionValue: string, checked: boolean) => { const next = checked ? [...selected, optionValue] : selected.filter((item) => item !== optionValue); if (value === undefined) setInner(next); onChange?.(next) }
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''}`}><Fieldset ref={ref} style={style} legend={legend} hint={hint} error={error}><div className={`govuk-checkboxes ${small ? 'govuk-checkboxes--small' : ''}`} data-module="govuk-checkboxes">{options.map((option) => <div key={option.value}><div className="govuk-checkboxes__item"><input {...inputProps} ref={inputRefs?.[option.value]} className="govuk-checkboxes__input" id={`${name}-${option.value}`} name={name} type="checkbox" value={option.value} checked={selected.includes(option.value)} disabled={option.disabled || inputProps?.disabled} onChange={(event) => update(option.value, event.target.checked)} /><label className="govuk-label govuk-checkboxes__label" htmlFor={`${name}-${option.value}`}>{option.label}</label>{option.hint && <div className="govuk-hint govuk-checkboxes__hint">{option.hint}</div>}</div>{option.conditional && selected.includes(option.value) && <div className="govuk-checkboxes__conditional">{option.conditional}</div>}</div>)}</div></Fieldset></div>
})

export interface RadioGroupProps extends Omit<ChoiceGroupProps, 'value' | 'defaultValue' | 'onChange'> { value?: string; defaultValue?: string; onChange?: (value: string) => void; inline?: boolean }
export const Radios = forwardRef<HTMLFieldSetElement, RadioGroupProps>(function Radios({ defaultValue, error, hint, inline = false, inputProps, inputRefs, legend, name, onChange, options, small = false, style, value }, ref) {
  const [inner, setInner] = useState(defaultValue); const selected = value ?? inner
  const update = (next: string) => { if (value === undefined) setInner(next); onChange?.(next) }
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''}`}><Fieldset ref={ref} style={style} legend={legend} hint={hint} error={error}><div className={`govuk-radios ${inline ? 'govuk-radios--inline' : ''} ${small ? 'govuk-radios--small' : ''}`} data-module="govuk-radios">{options.map((option) => <div key={option.value}><div className="govuk-radios__item"><input {...inputProps} ref={inputRefs?.[option.value]} className="govuk-radios__input" id={`${name}-${option.value}`} name={name} type="radio" value={option.value} checked={selected === option.value} disabled={option.disabled || inputProps?.disabled} onChange={() => update(option.value)} /><label className="govuk-label govuk-radios__label" htmlFor={`${name}-${option.value}`}>{option.label}</label>{option.hint && <div className="govuk-hint govuk-radios__hint">{option.hint}</div>}</div>{option.conditional && selected === option.value && <div className="govuk-radios__conditional">{option.conditional}</div>}</div>)}</div></Fieldset></div>
})

export interface DateValue { day?: string; month?: string; year?: string }
export interface DateInputProps { value?: DateValue; defaultValue?: DateValue; onChange?: (value: DateValue) => void; legend?: ReactNode; hint?: ReactNode; error?: ReactNode; namePrefix?: string; style?: CSSProperties; inputRefs?: Partial<Record<keyof DateValue, Ref<HTMLInputElement>>>; inputProps?: Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue' | 'onChange' | 'name' | 'id'> }
export const DateInput = forwardRef<HTMLFieldSetElement, DateInputProps>(function DateInput({ value, defaultValue = {}, onChange, legend = 'Date', hint, error, namePrefix = 'date', inputProps, inputRefs, style }, ref) {
  const [inner, setInner] = useState(defaultValue); const current = value ?? inner
  const change = (key: keyof DateValue) => (event: ChangeEvent<HTMLInputElement>) => { const next = { ...current, [key]: event.target.value }; if (value === undefined) setInner(next); onChange?.(next) }
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''}`}><Fieldset ref={ref} style={style} legend={legend} hint={hint} error={error}><div className="govuk-date-input">{([['day', 'Day', 2], ['month', 'Month', 2], ['year', 'Year', 4]] as const).map(([key, label, width]) => <div className="govuk-date-input__item" key={key}><label className="govuk-label govuk-date-input__label" htmlFor={`${namePrefix}-${key}`}>{label}</label><input {...inputProps} ref={inputRefs?.[key]} className={`govuk-input govuk-date-input__input govuk-input--width-${width} ${error ? 'govuk-input--error' : ''}`} id={`${namePrefix}-${key}`} name={`${namePrefix}-${key}`} inputMode="numeric" value={current[key] ?? ''} onChange={change(key)} /></div>)}</div></Fieldset></div>
})

export interface FileUploadProps extends InputHTMLAttributes<HTMLInputElement>, SemanticStyling<'root' | 'label' | 'hint' | 'error' | 'input'> { label: ReactNode; hint?: ReactNode; error?: ReactNode }
export const FileUpload = forwardRef<HTMLInputElement, FileUploadProps>(function FileUpload({ className = '', classNames, error, hint, id, label, style, styles, ...props }, ref) {
  const uid = useId(); const fieldId = id ?? `kvzd-upload-${uid.replaceAll(':', '')}`
  return <div className={`govuk-form-group ${error ? 'govuk-form-group--error' : ''} ${classNames?.root ?? ''}`.trim()} style={styles?.root}><Label htmlFor={fieldId} size="m" className={classNames?.label} style={styles?.label}>{label}</Label>{hint && <Hint className={classNames?.hint} style={styles?.hint}>{hint}</Hint>}{error && <ErrorMessage className={classNames?.error} style={styles?.error}>{error}</ErrorMessage>}<input {...props} ref={ref} id={fieldId} type="file" className={`govuk-file-upload ${error ? 'govuk-file-upload--error' : ''} ${classNames?.input ?? ''} ${className}`.trim()} style={{ ...styles?.input, ...style }} /></div>
})

export interface CharacterCountProps extends Omit<TextareaProps, 'maxLength' | 'styles' | 'classNames'>, SemanticStyling<'root' | 'formGroup' | 'label' | 'hint' | 'error' | 'textarea' | 'message'> { maxLength?: number; maxWords?: number }
export const CharacterCount = forwardRef<HTMLTextAreaElement, CharacterCountProps>(function CharacterCount({ maxLength = 200, maxWords, onChange, value, defaultValue, classNames, styles, ...props }, ref) {
  const [inner, setInner] = useState(String(defaultValue ?? '')); const text = String(value ?? inner)
  const count = useMemo(() => maxWords ? text.trim().split(/\s+/).filter(Boolean).length : text.length, [maxWords, text]); const maximum = maxWords ?? maxLength; const remaining = maximum - count
  return <div className={`govuk-character-count ${classNames?.root ?? ''}`.trim()} style={styles?.root} data-module="govuk-character-count"><Textarea {...props} styles={{ root: styles?.formGroup, label: styles?.label, hint: styles?.hint, error: styles?.error, textarea: styles?.textarea }} classNames={{ root: classNames?.formGroup, label: classNames?.label, hint: classNames?.hint, error: classNames?.error, textarea: classNames?.textarea }} ref={ref} value={text} onChange={(event) => { if (value === undefined) setInner(event.target.value); onChange?.(event) }} /><div className={`govuk-hint govuk-character-count__message ${remaining < 0 ? 'govuk-error-message' : ''} ${classNames?.message ?? ''}`.trim()} style={styles?.message} aria-live="polite">You have {Math.abs(remaining)} {maxWords ? 'word' : 'character'}{Math.abs(remaining) === 1 ? '' : 's'} {remaining < 0 ? 'too many' : 'remaining'}</div></div>
})

export interface PasswordInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'>, SemanticStyling<'root' | 'label' | 'wrapper' | 'input' | 'toggle'> { label?: ReactNode; showText?: string; hideText?: string; onVisibilityChange?: (visible: boolean) => void }
export const PasswordInput = forwardRef<HTMLInputElement, PasswordInputProps>(function PasswordInput({ className = '', classNames, label = 'Password', showText = 'Show', hideText = 'Hide', onVisibilityChange, style, styles, ...props }, ref) {
  const [visible, setVisible] = useState(false); const uid = useId(); const id = props.id ?? `kvzd-password-${uid.replaceAll(':', '')}`
  return <div className={`govuk-form-group govuk-password-input ${classNames?.root ?? ''}`.trim()} style={styles?.root}><Label htmlFor={id} className={classNames?.label} style={styles?.label}>{label}</Label><div className={`govuk-input__wrapper govuk-password-input__wrapper ${classNames?.wrapper ?? ''}`.trim()} style={styles?.wrapper}><input {...props} ref={ref} id={id} className={`govuk-input govuk-password-input__input ${classNames?.input ?? ''} ${className}`.trim()} style={{ ...styles?.input, ...style }} type={visible ? 'text' : 'password'} spellCheck={false} autoCapitalize="none" /><button className={`govuk-button govuk-button--secondary govuk-password-input__toggle ${classNames?.toggle ?? ''}`.trim()} style={styles?.toggle} type="button" aria-controls={id} aria-label={`${visible ? hideText : showText} password`} aria-pressed={visible} onClick={() => { const next = !visible; setVisible(next); onVisibilityChange?.(next) }}>{visible ? hideText : showText}</button></div></div>
})
